### ISSUE TITLE
Error when opening PhpStorm 8.0.2 after activating the plugin

### ISSUE THREAD

**Issue by serbanghita** [bogdananton/Sublime-testNameGenerator#8]
![tng-error](https://cloud.githubusercontent.com/assets/1106849/5788360/9598d444-9e39-11e4-8b7f-0fee9cf4b528.PNG)

PhpStorm 8.0.2
Windows 8.1 x64

I tried two times.

**Comment by bogdananton** [comment]
Please supply details about your Java version.
java -version

ex:
openjdk version "1.8.0_40-internal"
OpenJDK Runtime Environment (build 1.8.0_40-internal-b09)
OpenJDK 64-Bit Server VM (build 25.40-b13, mixed mode)
